### ISSUE TITLE
Marathon restarts app in POST /v2/apps

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1044]
Marathon creates deployment and restarts tasks in `POST /v2/apps` api endpoint even if configuration didn't change.

I think end user shouldn't care if `PUT /v2/apps/{appId}` should be used or `POST /v2/apps`. User describes desired state, it's for marathon to decide what to do.

**Comment by sttts** [comment]
Isn't that also fixed with #1007. Have you checked latest master or 0.7.6?

**Comment by bobrik** [comment]
I checked my PR rebased agains master where a9bccfa6f619984eed4145f22f1960e8cb78ec3f was on the top. Looks like #1007 made it into my version.

**Comment by bobrik** [comment]
Aha, I found an app that wasn't restarting and managed to make it restart.

The following ansible play generates new deployment on each run, but if I uncomment "cmd", no deployments happen if no changes were made. Looks like missing `cmd` is to blame.

```yaml
- hosts: web488
  roles:
    - role: topface.marathon
      marathon_url: http://web488:8080
      marathon_app:
        id: /topface/test/wtf
        # cmd: /app -listen 0.0.0.0:$PORT
        container:
          type: DOCKER
          docker:
            image: docker.core.tf/scruffy:2015-01-18.1
        cpus: 0.2
        mem: 64
        instances: 3
        ports:
          - 15002
        constraints:
          -
            - hostname
            - UNIQUE
```
