### ISSUE TITLE
Marathon should more gracefully handle connection issues with mesos

### ISSUE THREAD

**Issue by dkesler** [mesosphere/marathon#1140]
I've been fighting a bunch of weird inconsistent behavior in marathon over the past couple weeks, and after a couple days of investigation finally determined that the root cause was that some overly strict iptables rules were preventing mesos from properly communicating with marathon.  We were blocking basically anything other than 8080 and 5050, which (I'm assuming) prevented the mesos-master from hitting the marathon master on the other (non-8080) port that it's listening on.

The net effect of this is that unless the mesos leader and the marathon leader were on the same box, marathon would act in bizarre and unpredictable ways.  Marathon would reference old stopped tasks, deployments would stall without any feedback, and rolled back deployments would reappear.  Additionally, the marathon instance on the same box as the mesos leader would get spammed with re-registration requests (which presumably it rejected due to not being the leader).  While in this state, the frameworks ui in mesos indicated no problems and the marathon framework was marked as successfully registered.

It appears that in addition to occurring due to overly strict firewall rules, this type of issue can occur because of improperly set up hostnames resolving to localhost instead of the externally available ip address (see http://frankhinek.com/build-mesos-multi-node-ha-cluster/#note2).

Ideally, the marathon leader would be able to tell that it is not registered properly with mesos and provide some kind of visual warning.  Alternatively (or additionally), it would be nice if the mesos frameworks page indicated that the framework was not properly registered.  (I'm not sure if this is because of an issue in mesos thinking marathon accepted the reregistration when it didn't or if marathon isn't properly responding to the reregistration request to tell mesos that it's not accepting the reregistration).

**Comment by drexin** [comment]
Hi, thanks for letting us know. I think we could be more explicit in the Marathon UI. I don't know why Marathon is being shown a registered in the Mesos UI, but it could be that Mesos doesn't wait for the successful sending of the `FrameworkRegisteredMessage` to Marathon. I suggest you cross post this to the Mesos user list. The Mesos team will probably have an answer.

**Comment by dkesler** [comment]
This is the message that is appearing every second in the mesos leader's logs when the marathon leader is on a different box (in this case, 10.3.24.56)

Feb  4 12:57:02 dev-mesos-master1 mesos-master[12510]: I0204 12:57:02.232941 12534 master.cpp:1573] Re-registering framework 20141111-001826-924320522-5050-26663-0000 (marathon-0.7.6)  at scheduler-ad2f5b0d-db7a-42af-9dd2-030bd2118f88@10.3.24.56:44126
Feb  4 12:57:02 dev-mesos-master1 mesos-master[12510]: I0204 12:57:02.232961 12534 master.cpp:1602] Framework 20141111-001826-924320522-5050-26663-0000 (marathon-0.7.6) at scheduler-ad2f5b0d-db7a-42af-9dd2-030bd2118f88@10.3.24.56:44126 failed over
Feb  4 12:57:02 dev-mesos-master1 mesos-master[12510]: I0204 12:57:02.234338 12529 hierarchical_allocator_process.hpp:375] Activated framework 20141111-001826-924320522-5050-26663-0000
Feb  4 12:57:02 dev-mesos-master1 mesos-master[12510]: I0204 12:57:02.234993 12534 master.cpp:3843] Sending 4 offers to framework 20141111-001826-924320522-5050-26663-0000 (marathon-0.7.6) at scheduler-ad2f5b0d-db7a-42af-9dd2-030bd2118f88@10.3.24.56:44126
Feb  4 12:57:02 dev-mesos-master1 mesos-master[12510]: I0204 12:57:02.235301 12528 master.cpp:789] Framework 20141111-001826-924320522-5050-26663-0000 (marathon-0.7.6) at scheduler-ad2f5b0d-db7a-42af-9dd2-030bd2118f88@10.3.24.56:44126 disconnected
Feb  4 12:57:02 dev-mesos-master1 mesos-master[12510]: I0204 12:57:02.235327 12528 master.cpp:1752] Disconnecting framework 20141111-001826-924320522-5050-26663-0000 (marathon-0.7.6) at scheduler-ad2f5b0d-db7a-42af-9dd2-030bd2118f88@10.3.24.56:44126
Feb  4 12:57:02 dev-mesos-master1 mesos-master[12510]: I0204 12:57:02.235337 12528 master.cpp:1768] Deactivating framework 20141111-001826-924320522-5050-26663-0000 (marathon-0.7.6) at scheduler-ad2f5b0d-db7a-42af-9dd2-030bd2118f88@10.3.24.56:44126
Feb  4 12:57:02 dev-mesos-master1 mesos-master[12510]: I0204 12:57:02.235680 12533 hierarchical_allocator_process.hpp:405] Deactivated framework 20141111-001826-924320522-5050-26663-0000

It sounds like maybe marathon is telling mesos where to contact the leader, mesos assumes that it will be able to connect and marks it as registered, but then mesos can't reach the marathon leader and disconnects the framework, starting the re-registration cycle all over again.

I'll crosspost to the mesos list and see what they have to say.

**Comment by ccll** [comment]
You saved my day!!!

**Comment by memelet** [comment]
I just cleared up the same problem with overly restrictive security-groups on ec2. The sympton was that deployed tasks would hang in deploy. Then I found in the mesos-master log repeating messages that marathon was re-registered. Fixing the security-groups immediately caused the hanging deploys to finish. But I agree, the marathon UI gave no indication of any problem other than the hung deploys.

**Comment by jolexa** [comment]
@memelet Regarding "fixing the security-groups" - ultimately, what did you end up doing? It appears to me that master will send offers to the marathon at a random(?) port

**Comment by memelet** [comment]
@jolexa Do you mean that master will use a random port to send the offer, or that master will offer resources for ramdom ports?

My mesos master/slave security groups are shown below. I think there is still some tightening to do.

(fyi: I have marathon on 5080)

```
      ec2_group:
        name: "{{mesos_master_sg_name}}"
        rules:
          - {proto: tcp, from_port:    0, to_port: 65535, group_name: "{{mesos_master_sg_name}}"}
          - {proto: tcp, from_port: 2181, to_port:  2181, group_name: "{{mesos_slave_sg_name}}", group_desc: "{{mesos_slave_sg_desc}}"}
          - {proto: tcp, from_port: 5050, to_port:  5050, group_name: "{{mesos_slave_sg_name}}", group_desc: "{{mesos_slave_sg_desc}}"}
          - {proto: tcp, from_port: 5051, to_port:  5051, group_name: "{{mesos_slave_sg_name}}", group_desc: "{{mesos_slave_sg_desc}}"}
          - {proto: tcp, from_port: 5080, to_port:  5080, group_name: "{{mesos_slave_sg_name}}", group_desc: "{{mesos_slave_sg_desc}}"}
        rules_egress:
          - {proto: tcp, from_port:    0, to_port: 65535, group_name: "{{mesos_master_sg_name}}"}
          - {proto: tcp, from_port: 5050, to_port:  5050, group_name: "{{mesos_slave_sg_name}}", group_desc: "{{mesos_slave_sg_desc}}"}
          - {proto: tcp, from_port: 5051, to_port:  5051, group_name: "{{mesos_slave_sg_name}}", group_desc: "{{mesos_slave_sg_desc}}"}
          - {proto: tcp, from_port:    0, to_port: 65535, group_name: "{{mesos_slave_sg_name}}", group_desc: "{{mesos_slave_sg_desc}}"} # For health checks #TODO{security} Limit to ports allocated to mesos
```

```
      ec2_group:
        name: "{{mesos_slave_sg_name}}"
        rules:
          - {proto: tcp, from_port: 5050, to_port:  5050, group_name: "{{mesos_master_sg_name}}", group_desc: "{{mesos_master_sg_desc}}"}
          - {proto: tcp, from_port: 5051, to_port:  5051, group_name: "{{mesos_master_sg_name}}", group_desc: "{{mesos_master_sg_desc}}"}
          - {proto: tcp, from_port:    0, to_port: 65535, group_name: "{{mesos_master_sg_name}}", group_desc: "{{mesos_master_sg_name}}"} # For health checks #TODO{security} Limit to ports allocated to mesos
        rules_egress:
          - {proto: tcp, from_port:  2181, to_port:  2181, group_name: "{{mesos_master_sg_name}}",    group_desc: "{{mesos_master_sg_desc}}"}
          - {proto: tcp, from_port:  5050, to_port:  5050, group_name: "{{mesos_master_sg_name}}",    group_desc: "{{mesos_master_sg_desc}}"}
          - {proto: tcp, from_port:  5051, to_port:  5051, group_name: "{{mesos_master_sg_name}}",    group_desc: "{{mesos_master_sg_desc}}"}
          - {proto: tcp, from_port:  5080, to_port:  5080, group_name: "{{mesos_master_sg_name}}",    group_desc: "{{mesos_master_sg_desc}}"}
```
