### ISSUE TITLE
Running marathon 0.8.2-RC2 in local development mode fails 

### ISSUE THREAD

**Issue by solarkennedy** [mesosphere/marathon#1507]
I'm trying to run marathon 0.8.2-rc2 in development mode in docker for some integration tests.

0.8.2-RC2 fails reliably with this output:
http://pastebin.com/3urBuXYS

It is a little hard for me to tell what the actual problem is. Here is my best guess at the cause:
```
marathon_1  | [2015-05-12 03:30:21,205] INFO Migration for storage: Version(0, 0, 0) to current: Version(0, 8, 2): apply change for version: Version(0, 5, 0)  (mesosphere.marathon.state.Migration:53)
marathon_1  | [2015-05-12 03:30:21,210] INFO Migration for storage: Version(0, 0, 0) to current: Version(0, 8, 2): apply change for version: Version(0, 7, 0)  (mesosphere.marathon.state.Migration:53)
marathon_1  | [2015-05-12 03:30:21,215] ERROR Failed to take over leadership: java.lang.NullPointerException (mesosphere.marathon.MarathonSchedulerService:268)
marathon_1  | [2015-05-12 03:30:21,215] ERROR Migration failed! java.lang.NullPointerException (mesosphere.marathon.state.Migration:70)
```

RC1 does *not* have these lines. (RC1 run for reference http://pastebin.com/NwDm7fXs)

This can be reproduced with this fig.yaml:
```
zookeeper:
  image: jplock/zookeeper
  ports:
    - 2181

marathon:
  image: mesosphere/marathon:v0.8.2-RC2
  ports:
    - 8080
  links:
    - zookeeper
  command: '--master local --zk zk://zookeeper:2181/marathon'
```
and `fig up`

cc @mrtyler @evankrall
