### ISSUE TITLE
Health Check issue. 

### ISSUE THREAD

**Issue by mahesh3267** [mesosphere/marathon#1744]
Hi All, 

Myself having trouble with Health Check for docker container in marathon, by using following file iam able to deploy the container through marathon, but getting RED health status. 

Please let me know, if we need any changes to be done in the following configuration to get Health Status GREEN.

{
  "id": "bridged-webapp",
  "cmd": "python3 -m http.server 8080",
  "cpus": 0.5,
  "mem": 64.0,
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "python:3",
      "network": "BRIDGE",
      "portMappings": [
        { "containerPort": 8080, "hostPort": 0, "servicePort": 0, "protocol": "tcp" }
      ]
    }
  },
  "healthChecks": [
    {
      "protocol": "COMMAND",
      "command": { "value": "echo http://$HOST:$PORT0 >/tmp/test.log && curl -f -X GET http://$HOST:$PORT0" },
      "gracePeriodSeconds": 10,
      "intervalSeconds": 10,
      "timeoutSeconds": 5,
      "maxConsecutiveFailures": 2
    }
  ]
}

**Comment by kolloch** [comment]
Can you connect to the application manually?

**Comment by mahesh3267** [comment]
Yes iam able to run container and able to browse with host mapped port
number. Only having issue with health check showing in RED. Pls help.

**Comment by mahesh3267** [comment]
Hi Kolloch,

Thanks for your update. 

Yes iam able to run container and able to browse with host mapped port number. Only having issue with health check showing in RED. Pls help

**Comment by kolloch** [comment]
Hello @mahesh3267,

I just checked your app definition on an internal cluster of ours. It does work. What version of Marathon/Mesos are you using? Are you running the slave process on the same host as docker (so you are NOT using boot2docker or something like that and running mesos-slave under Mac OS)?

If you do use boot2docker, could you please provide a documentation update PR which points out this particular problem? Thanks!

**Comment by kolloch** [comment]
Just to be sure, I tested it on 0.8.2 as well.

**Comment by mahesh3267** [comment]
Myself having Linux vm with Docker installed, so using docker-compose to launch the zookeper, marathon, mesos-master & slaves. Please find the following configuration. 

zookeeper:
  image: jplock/zookeeper:3.4.5
  ports:
    - "2181"
master:
  image: redjack/mesos-master:0.21.0
  hostname: master
  links:
    - zookeeper:zookeeper
  environment:
    - MESOS_ZK=zk://zookeeper:2181/mesos
    - MESOS_QUORUM=1
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_LOG_DIR=/var/log
  ports:
    - "5050:5050"
marathon:
#image: garland/mesosphere-docker-marathon
  image: mesosphere/marathon
  links:
    - zookeeper:zookeeper
  ports:
    - "8089:8080"
# this image does not respect MARATHON_ env variables, so adding the params via command
  command: --master zk://zookeeper:2181/mesos --zk zk://zookeeper:2181/marathon

slave1:
  image: redjack/mesos-slave:0.21.0
  links:
    - zookeeper:zookeeper
    - master:master
  environment:
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
  volumes:
    - /var/run/docker.sock:/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /sys:/sys:ro
    - mesosslace-stuff:/var/log
  expose:
    - "5051"

slave2:
  image: redjack/mesos-slave:0.21.0
  links:
    - zookeeper:zookeeper
    - master:master
  environment:
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
  volumes:
    - /var/run/docker.sock:/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /sys:/sys:ro
    - mesosslace-stuff:/var/log
  expose:
    - "5051"
slave3:
  image: redjack/mesos-slave:0.21.0
  links:
    - zookeeper:zookeeper
    - master:master
  environment:
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
  volumes:
    - /var/run/docker.sock:/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /sys:/sys:ro
    - mesosslace-stuff:/var/log
  expose:
    - "5051"

**Comment by mahesh3267** [comment]
Myself using linux virtual machine with docker, using docker-compose.yml to launch mesos cluster. please find the following configuration. 
```
zookeeper:
  image: jplock/zookeeper:3.4.5
  ports:
    - "2181"
master:
  image: redjack/mesos-master:0.21.0
  hostname: master
  links:
    - zookeeper:zookeeper
  environment:
    - MESOS_ZK=zk://zookeeper:2181/mesos
    - MESOS_QUORUM=1
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_LOG_DIR=/var/log
  ports:
    - "5050:5050"
marathon:
#image: garland/mesosphere-docker-marathon
  image: mesosphere/marathon
  links:
    - zookeeper:zookeeper
  ports:
    - "8089:8080"
# this image does not respect MARATHON_ env variables, so adding the params via command
  command: --master zk://zookeeper:2181/mesos --zk zk://zookeeper:2181/marathon

slave1:
  image: redjack/mesos-slave:0.21.0
  links:
    - zookeeper:zookeeper
    - master:master
  environment:
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
  volumes:
    - /var/run/docker.sock:/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /sys:/sys:ro
    - mesosslace-stuff:/var/log
  expose:
    - "5051"

slave2:
  image: redjack/mesos-slave:0.21.0
  links:
    - zookeeper:zookeeper
    - master:master
  environment:
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
  volumes:
    - /var/run/docker.sock:/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /sys:/sys:ro
    - mesosslace-stuff:/var/log
  expose:
    - "5051"
slave3:
  image: redjack/mesos-slave:0.21.0
  links:
    - zookeeper:zookeeper
    - master:master
  environment:
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
  volumes:
    - /var/run/docker.sock:/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /sys:/sys:ro
    - mesosslace-stuff:/var/log
  expose:
    - "5051"
```
