### ISSUE TITLE
Container path containing slashes makes application hang on wait [Version 1.0.0-RC1]

### ISSUE THREAD

**Issue by jaimelive** [mesosphere/marathon#3589]
It seems that, on Marathon Version 1.0.0-RC1, if I submit a task with a container path containing slashes
```yml
        "volumes": [
          {
            "containerPath": "/data",
            "mode": "RW",
            "persistent": {
              "size": 1024
            } 
          }
        ]
```
the taks will hang in Waiting and a huge outstanding offer (6.4GB, about 90% off all ram in a node) will be created. After that no more tasks are scheduled on that node until restart.

The documentation is still not clear on the reason behind this, but not allowing nested paths seems a bit limiting and creates the need to alter applications and images.
