### ISSUE TITLE
Marathon memory grows unbounded

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#3964]
Marathon 1.1.1, two instances of the same framework (one leader and one failover).

```yaml
    env:
      JAVA_OPTS: -Xms1g -Xmx1g
      MARATHON_MASTER: zk:/foo:2181/mesos
      MARATHON_ZK: zk://foo:2181/marathons/misc
      MARATHON_ZK_MAX_VERSIONS: '10'
      MARATHON_FRAMEWORK_NAME: marathon-misc
      MARATHON_DECLINE_OFFER_DURATION: '3600000'
      MARATHON_MESOS_LEADER_UI_URL: http://foo.org
```

24h timespan:

<img width="1259" alt="screen shot 2016-06-07 at 08 50 46" src="https://cloud.githubusercontent.com/assets/89186/15849977/44ccbcfe-2c8d-11e6-9d72-8c43eca8b653.png">

Same happened on 0.15.3.
