### ISSUE TITLE
Some properties aren't properly marked as optional in RAML

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#4811]
Some of the health check properties as well as potentially others aren't properly marked as optional values. This leads to confusion as they aren't required and to validation issues in the DC/OS Service UI which is using RAML to validate app definitions.

**Example**
```
 maxConsecutiveFailures:
        type: integer
        format: int32
        description: |
          Number of consecutive health check failures after which the
          unhealthy task should be killed.
        minimum: 0
        default: 3
```
_https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/public/api/v2/types/healthCheck.raml#L103_

`maxConsecutiveFailures` has a default values and is as thus implicitly optional but is not marked as an optional value.
