### ISSUE TITLE
Wrong Endpoint.hostPort type in the network.raml

### ISSUE THREAD

**Issue by wavesoft** [mesosphere/marathon#4817]
On the `Endpoint.hostPort` type, there is a `minimum: 0` definition as seen below:

```yml
      hostPort?:
        type: numbers.Port
        description: |
          Mapped port on the host.
          All host ports are allocated from resource offers.
        usage: Specify 0 to tell Marathon to dynamically allocate a host port.
        minimum: 0
```

Unfortunately, this does not validate correctly with the RAML parser we use in the UI, since the `minimum` is not considered when already using a custom numeric type. 

However, I noticed that there is already the `EphemeralPort` in the `numberTypes.raml` that provides the minimum 0, so you could use:

```yml
      hostPort?:
        type: numbers.EphemeralPort
        description: |
          Mapped port on the host.
          All host ports are allocated from resource offers.
        usage: Specify 0 to tell Marathon to dynamically allocate a host port.
```
