### ISSUE TITLE
How to post two apps in the same host??

### ISSUE THREAD

**Issue by sivaramsk** [mesosphere/marathon#894]
Say I have two containers, and I want both of them to run in the same host. Is this possible? We can achieve this partially by using "Constraints rack_id:CLUSTER:rack-1". But that restricts it to that particular host and if that host fails, the task will not move around. Any ideas?

**Comment by jhmartin** [comment]
It sounds like you are looking for the equivalent of a Kubernetes Pod, which doesn't appear to exist in Marathon.

**Comment by dpetzel** [comment]
I had posted a similar question on the mailing a while back, as I was looking for the exact same functionality: https://groups.google.com/forum/#!topic/marathon-framework/iWHdoSomFIM

**Comment by sttts** [comment]
:+1:

**Comment by jhmartin** [comment]
This could also perhaps be phrased as 'For each (Docker) task X, schedule tasks A,B,C to run on the same host and be linked in a certain way. If any of A or B fail, terminate the entire set and recreate. If C fails, respawn C'

**Comment by sttts** [comment]
Additionally it should be possible to phrase: 'If there is at least one task X, schedule task A,B,C'.

**Comment by jhmartin** [comment]
The difference is whether each X gets an A,B,C or all X's share a A,B,C.  I can see cases for both.

**Comment by vidarl** [comment]
Any plans for adding pod support in marathon?

**Comment by dsiegel** [comment]
I'm filling the "pod" use-case using supervisord. It's not ideal IMO. I'd prefer having 1 process per docker. I can't do that without support for launching a group of containers with port and volume links.

**Comment by salimane** [comment]
any update on how this could be achieved as of current versions ?
Thanks

**Comment by mikljohansson** [comment]
There's the beginnings of a Docker-Compose Mesos executor that could solve this case at https://github.com/mohitsoni/compose-executor

**Comment by salimane** [comment]
@mikljohansson interesting, will check it out :)

**Comment by junneyang** [comment]
any update on how this could be achieved as of current versions ?
Thanks

**Comment by salimane** [comment]
@junneyang something that could kinda help is : 
```

  id: "/my/service"
  dependencies:
    - "/my/other_service"
  instances: 2
  upgradeStrategy:
    minimumHealthCapacity: 0.5
    maximumOverCapacity: 0.2
  cpus: 0.50
  mem: 1024.0
```

**Comment by junneyang** [comment]
@salimane 
you mean the dependencies field could make the apps deploy on the same node?
very thanks!

**Comment by salimane** [comment]
Oh i forgot to add the constraints field like : 

```
  id: "/my/service"
  dependencies:
    - "/my/other_service"
  instances: 2
  upgradeStrategy:
    minimumHealthCapacity: 0.5
    maximumOverCapacity: 0.2
  cpus: 0.50
  mem: 1024.0
  constraints: [["hostname", "LIKE", "hostname-my-server-.*.company.net"], ["hostname", "UNIQUE"]]
```
